#!/bin/sh

set -e

case "$1" in
    (configure)
#    if test -z "$2"; then
	    add-shell /bin/zsh-static
#    fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
	exit 0
    ;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 0
    ;;
esac

update-alternatives --remove zsh-static /bin/zsh4-static
update-alternatives --remove zsh-static /bin/zsh5-static

#DEBHELPER#

exit 0
